### ISSUE TITLE
Failed deployment

### ISSUE THREAD

**Issue by chzbrgr71** [Azure/reddog-containerapps#12] opened 2021-11-22 17:26 UTC
My deployment ran for about 15 minutes and got the below error. 

It looks like everything deployed except the ca-reddog--loyalty-service which has this error in ARM: `"message": "Failed to provision revision for container app 'loyalty-service'. Error details: Operation expired`

```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"{\\r\\n  \\\"status\\\": \\\"Failed\\\",\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n    \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n    \\\"details\\\": [\\r\\n      {\\r\\n        \\\"code\\\": \\\"90008\\\",\\r\\n        \\\"message\\\": \\\"Failed to provision revision for container app 'loyalty-service'. Error details: Operation expired.\\\"\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}
```

**Comment by kendallroden** [comment] 2021-11-22 20:17
happens sometimes.. I had this happen but for makeline. I think it's an issue with container apps and transient failures. If you delete and redeploy the service it usually goes through. @alicejgibbons I know you mentioned this happens sometimes for you.

**Comment by SOE-YoungS** [comment] 2021-11-29 20:17
This error is happening when running an update via Azure CLI as an Azure Devops task. 

Creating a new revision via the Azure Portal works fine. Running the Azure Devops Pipeline again after a successful deployment via the Portal, again results in this error. 

No other errors / failed calls are found in the debug output (beyond a few "Operation Expired" responses near the end of the output).

In my case, I have two container apps, the second requires the other apps public URL to talk to this one (which is failing to update). Deleting the container app really isn't desirable in this instance as it would force a need to update the second container which may also be struck by this error...

**Comment by lgmorand** [comment] 2021-12-16 16:42
The first time it worked but then I deleted everything (the RG) and then running the run.sh. After 30 minutes (!!) I got a failing deployment 

> {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"{\\r\\n  \\\"status\\\": \\\"Failed\\\",\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n    \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n    \\\"details\\\": [\\r\\n      {\\r\\n        \\\"code\\\": \\\"90008\\\",\\r\\n        \\\"message\\\": \\\"Failed to provision revision for container app 'bootstrapper'. Error details: Code: 90714, ExtendedCode: 90714, Message: Error provisioning the container app. Container 'bootstrapper' failed to start-up. Please check Log Analytics workspace for container logs..\\\"\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}


What is weird is:
- running the script again, it fails exactly at the same place (bootstrapper)
- in Azure Web Portal, the Container App says " deployment failed"
- in Revision management, the revision is marked as successful ("provisioned")

What I needed to do to fix it:
- delete manually the Container App
- run the script again

**Comment by lynn-orrell** [comment] 2021-12-17 04:17
As @kendallroden stated previously, there seems to be some transient failures that are occurring sometimes during the provisioning process. Typically, you can just execute run.sh again and it will pick up where it left off and run to completion. We will continue to monitor the situation.

As for the length of time it takes to deploy, the long pole is the redis cache (which we may look at swapping out due to provisioning time). If you go have a look at the deployments blade under the resource group you will see what I'm talking about. Here is a screenshot for reference.
![image](https://user-images.githubusercontent.com/2810722/146488087-5f74fc23-3d88-45fb-b186-87d410066214.png)

**Comment by lgmorand** [comment] 2022-01-04 10:46
@lynn-orrell there is something more complex than that. Indeed it failed on the first try because Redis took 20min to provision but if we run the script again, once all PaaS services are up and running, several containers apps continue to fail and take more than 10min to provision. We also tried in several Azure regions just in case.

None of us success to deploy it (@mavilleg @kevingbb )

we also tried to delete the containers apps (either 3 of them or all of them) before running the script again but it fails every time and that's the deployment of the containers apps itself the issue (even after 4-5 tries).

Any way to get logs on containers app side to understand what could be the issue ?

![erreor](https://user-images.githubusercontent.com/6757079/148046709-22274686-ed54-4656-98b2-24fb26aa483f.png)


Last point: deploying manually (command line) a simple hello world app on the same ACA env takes few minutes but is successful. I don't know if the issue is not Dapr related

**Comment by chzbrgr71** [comment] 2022-01-04 17:03
It does seem like some updates in the service are causing issues with this deployment. I just ran one now and it partially worked. My SQL database was deployed and the bootstrapper created all of the tables. 

But none of the services work. I checked some container apps logs, but I don't see any issues there. 

You can get logs with the following commands. 

```bash
# change the RG and LA name
export LOG_ANALYTICS_WORKSPACE_CLIENT_ID=`az monitor log-analytics workspace show --query customerId -g reddog-ugau75ushmbiq -n reddog-ugau75ushmbiq --out tsv`

# change the service name below
az monitor log-analytics query \
  --workspace $LOG_ANALYTICS_WORKSPACE_CLIENT_ID \
  --analytics-query "ContainerAppConsoleLogs_CL | where ContainerAppName_s == 'order-service' | project ContainerAppName_s, Log_s, TimeGenerated "
```

**Comment by lgmorand** [comment] 2022-01-04 17:11
Thanks Brian for testing. We have the same behavior We thought that the deployment could be marked as failed but in fact deployment could be successful inside the cluster. But if we try to reach the public endpoint, the page does not load.

For each container, logs say that Dapr is shutting down. 

`1/4/2022, 10:27:53.585 AM	order-service	time="2022-01-04T10:27:52.133423707Z" level=info msg="Shutting down actor" app_id=order-service instance=order-service--7gdhysy-5b864b8f77-zp9s6 scope=dapr.runtime type=log ver=edge	
1/4/2022, 10:27:53.585 AM	order-service	time="2022-01-04T10:27:52.255031484Z" level=info msg="dapr shutting down. Waiting 5s to finish outstanding operations" app_id=order-service instance=order-service--7gdhysy-5b864b8f77-zp9s6 scope=dapr.runtime type=log ver=edge	
1/4/2022, 10:27:53.760 AM	order-service	[2022-01-04 10:27:52.146 INF] [Microsoft.Hosting.Lifetime] Application is shutting down...`

**Comment by kendallroden** [comment] 2022-01-04 19:37
@torosent can you have someone on the engineering team please assist here and help troubleshoot?

**Comment by kendallroden** [comment] 2022-01-04 19:37
@lgmorand what is your env name?

**Comment by lgmorand** [comment] 2022-01-04 20:55
reddog-vl7cflbopmqhu
sub id: 6c9dc160-dca4-47cb-9e76-ed16a4b4edb1

**Comment by torosent** [comment] 2022-01-04 23:40
Thanks. We are investigating and will report back.

**Comment by Lemraj** [comment] 2022-01-09 20:43
Hi folks,
I wanted to use the new Azure Container Apps, but i get an error when creating this. The error i get is:
`{
    "status": "Failed",
    "error": {
        "code": "90008",
        "message": "Failed to provision revision for container app '<ContainerName>'. Error details: Operation expired."
    }
}`

Any idea why? thanks.

**Comment by alicejgibbons** [comment] 2022-01-10 17:16
FYI this is a known issue on Container Apps due to dapr component scoping and is being investigated by the Product Group! We will post an update here when we have one, thanks!

**Comment by Lemraj** [comment] 2022-01-10 20:51
@alicejgibbons is this also in my case? thanks :)

**Comment by udayansarma** [comment] 2022-01-12 21:27
My experience is that you can have only one app with dapr enabled in an environment.

**Comment by lynn-orrell** [comment] 2022-01-12 21:31
> My experience is that you can have only one app with dapr enabled in an environment. This is probably a bug.

If that's the case, this is a fairly new bug that has been introduced. I know there was a bug where all dapr components defined across all container apps in an environment were attempting to be loaded by each container app. Maybe the initial attempt to remedy this introduced this bug? @kendallroden  @torosent

**Comment by frkim** [comment] 2022-01-17 14:56
Hi, I'm facing the same issue. :(
Any news from the product group?

**Comment by kendallroden** [comment] 2022-02-09 03:19
This was due to the dapr components move and as discussed should be resolved for now while we are working on the components move to env level

**Closed by kendallroden** 2022-02-09 03:19 UTC
